modLoader="javafml"
loaderVersion="[33,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Su5eD/Somnia/issues/"
[[mods]]
modId="somnia"
version="${version}"
displayName="Somnia Awoken"
displayURL="https://github.com/Su5eD/Somnia"
logoFile="logo.png"
credits="MALfunction84 and Kingrunes, authors of the previous versions"
authors="Su5eD"
description='''
Simulating the world while you sleep
'''
[[dependencies.somnia]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.16.5]"
    ordering="NONE"
    side="BOTH"
